// @vitest-environment node
import { describe, it, expect } from 'vitest'
import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { parsePdfBuffer } from '~~/server/services/PDFImportService'

// Fully synthetic statement generated by scripts/make-synthetic-import-fixture.mjs;
// mirrors the POS export shape (T-rows, '-' orphan rows, 'RM -' voids, 总计 header).
const fixture = fileURLToPath(new URL('../../fixtures/sample-import.pdf', import.meta.url))

describe('PDFImportService.parsePdfBuffer', () => {
  it('parses the synthetic statement fixture', async () => {
    const buf = await readFile(fixture)
    const r = await parsePdfBuffer(buf)
    expect(r.ambassadorHint).toMatch(/DEMOAGENT/i)
    expect(r.headerTotal).toBeCloseTo(321555.05, 2)
    expect(r.rows.length).toBe(67)
    const sum = r.rows.reduce((a, x) => a + x.amount, 0)
    expect(Math.abs(sum - r.headerTotal)).toBeLessThan(0.05)
    expect(r.rows[0]).toMatchObject({
      date: '2026-04-01',
      externalOrderId: 'T260401100000000',
      tableNumber: 'L11',
      amount: 1454.55,
    })
  })

  it('derives synthetic ids for orphan rows and skips RM - rows', async () => {
    const buf = await readFile(fixture)
    const r = await parsePdfBuffer(buf)
    const orphans = r.rows.filter(x => x.externalOrderId.startsWith('M-'))
    expect(orphans).toHaveLength(2)
    expect(r.rows.every(x => x.amount > 0)).toBe(true)
    expect(r.rows.some(x => x.externalOrderId === 'T260420999999999')).toBe(false)
  })
})
